export default function AnimatedPage() {
  return (
    <svg viewBox="0 0 64 64" className="w-12 h-12 text-yellow-400">
      <rect
        x="10"
        y="8"
        width="44"
        height="48"
        fill="none"
        stroke="currentColor"
        strokeWidth="4"
        strokeDasharray="200"
        strokeDashoffset="200"
      >
        <animate
          attributeName="stroke-dashoffset"
          values="200;0;0;200"
          keyTimes="0;0.3;0.7;1"
          dur="4s"
          repeatCount="indefinite"
        />
      </rect>
      <line
        x1="16"
        y1="20"
        x2="48"
        y2="20"
        stroke="white"
        strokeWidth="2"
        strokeDasharray="32"
        strokeDashoffset="32"
      >
        <animate
          attributeName="stroke-dashoffset"
          values="32;0;0;32"
          keyTimes="0;0.3;0.7;1"
          dur="4s"
          repeatCount="indefinite"
        />
      </line>
      <line
        x1="16"
        y1="28"
        x2="48"
        y2="28"
        stroke="white"
        strokeWidth="2"
        strokeDasharray="32"
        strokeDashoffset="32"
      >
        <animate
          attributeName="stroke-dashoffset"
          values="32;0;0;32"
          keyTimes="0;0.3;0.7;1"
          dur="4s"
          repeatCount="indefinite"
        />
      </line>
    </svg>
  );
}
