export default function AnimatedStack() {
  return (
    <svg viewBox="0 0 64 64" className="w-12 h-12 text-indigo-400">
      <rect
        x="12"
        y="12"
        width="40"
        height="10"
        fill="none"
        stroke="currentColor"
        strokeWidth="4"
        strokeDasharray="100"
        strokeDashoffset="100"
      >
        <animate
          attributeName="stroke-dashoffset"
          values="100;0;0;100"
          keyTimes="0;0.3;0.7;1"
          dur="4s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x="12"
        y="27"
        width="40"
        height="10"
        fill="none"
        stroke="currentColor"
        strokeWidth="4"
        strokeDasharray="100"
        strokeDashoffset="100"
      >
        <animate
          attributeName="stroke-dashoffset"
          values="100;0;0;100"
          keyTimes="0;0.3;0.7;1"
          dur="4s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x="12"
        y="42"
        width="40"
        height="10"
        fill="none"
        stroke="currentColor"
        strokeWidth="4"
        strokeDasharray="100"
        strokeDashoffset="100"
      >
        <animate
          attributeName="stroke-dashoffset"
          values="100;0;0;100"
          keyTimes="0;0.3;0.7;1"
          dur="4s"
          repeatCount="indefinite"
        />
      </rect>
    </svg>
  );
}
